04.C#Web/C# MVC Frameworks - ASP.NET Core/00.HomeworksChecks/07.ViewsAndLayouts.Chushka/2best/MyChushka/MyChushka.WebApp/ViewModels/Home/IndexNodeViewModel.cs
namespace MyChushka.WebApp.ViewModels.Home
{
    public class IndexNodeViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public decimal Price { get; set; }

        public string ShortDescription
        {
            get
            {
                if (this.Description.Length > 50)
                {
                    var result = this.Description.Substring(0, 50);

                    return result + "...";
                }

                return this.Description;
            }
        }
    }
}

04.C#Web/C# MVC Frameworks - ASP.NET Core/00.HomeworksChecks/07.ViewsAndLayouts.Chushka/2best/MyChushka/MyChushka.WebApp/Components/ProductNodeViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyChushka.WebApp.Data;
using MyChushka.WebApp.ViewModels.Home;

namespace MyChushka.WebApp.Components
{
    //[ViewComponent(Name = "ProductNode")]
    public class ProductNodeViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext db;

        public ProductNodeViewComponent(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IViewComponentResult Invoke(int id)
        {
            var model = this.db.Products
                .Where(p => p.Id == id)
                .Select(p => new IndexNodeViewModel
                {
                    Id = p.Id,
                    Description = p.Description,
                    Name = p.Name,
                    Price = p.Price
                })
                .FirstOrDefault();

            return this.View(model);
        }
    }
}

04.C#Web/C# MVC Frameworks - ASP.NET Core/00.HomeworksChecks/07.ViewsAndLayouts.Chushka/2best/MyChushka/MyChushka.WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyChushka.WebApp.Data;
using MyChushka.WebApp.ViewModels;
using MyChushka.WebApp.ViewModels.Home;

namespace MyChushka.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext db;

        public HomeController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            if (!this.User.Identity.IsAuthenticated)
            {
                return this.View("AnonymousIndex");
            }

            var model = this.db.Products
                .Select(p => new IndexNodeViewModel
                {
                    Description = p.Description,
                    Price = p.Price,
                    Name = p.Name,
                    Id = p.Id
                })
                .ToList();

            return this.View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

04.C#Web/C# MVC Frameworks - ASP.NET Core/00.HomeworksChecks/07.ViewsAndLayouts.Chushka/2best/MyChushka/MyChushka.WebApp/Views/Home/AnonymousIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<main>
    <div class="jumbotron mt-3 chushka-bg-color">
        <h1>Welcome to Chushka Universal Web Shop</h1>
        <hr class="bg-white" />
        <h3><a asp-controller="Users" asp-action="Login" class="nav-link-dark">Login</a> if you have an account.</h3>
        <h3><a asp-controller="Users" asp-action="Register" class="nav-link-dark">Register</a> if you don't.</h3>
    </div>
</main>

04.C#Web/C# MVC Frameworks - ASP.NET Core/00.HomeworksChecks/07.ViewsAndLayouts.Chushka/2best/MyChushka/MyChushka.WebApp/Views/Home/Index.cshtml
@using MyChushka.WebApp.Constants
@model List<MyChushka.WebApp.ViewModels.Home.IndexNodeViewModel>

@{
    ViewData["Title"] = "Home Page";
}

<main class="mt-3 mb-5">
    <div class="container-fluid text-center">
        @if (this.User.IsInRole(MyConst.AdminRole))
        {
            <h2>Greetings, Admin-@this.User.Identity.Name!</h2>
            <h4>Enjoy your work today!</h4>
        }
        else
        {
            <h2>Greetings, @this.User.Identity.Name!</h2>
            <h4>Feel free to view and order any of our products.</h4>
        }
    </div>
    <hr class="hr-2 bg-dark" />
    <div class="container-fluid product-holder">
        <div class="row d-flex justify-content-around">
            @for (int i = 0; i < this.Model.Count; i++)
            {
                var item = this.Model[i];

                if (i > 0 && i % 5 == 0)
                {
                    @:</div>
                    @:<div class="row d-flex justify-content-around mt-4">
                }

                <vc:product-node id="@item.Id"></vc:product-node>
            }
        </div>
    </div>
</main>