04.C#Web/C# MVC Frameworks - ASP.NET Core/05.ExerciseIntroductionToASP.NetCore/Panda/Panda.Web/Panda.Web/Controllers/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Panda.Model;
using Panda.Services.Contracts;
using Panda.Web.Models;

namespace Panda.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPackageService _packageService;
        private readonly UserManager<PandaUser> _currentUser;

        public HomeController(IPackageService packageService, UserManager<PandaUser> currentUser)
        {
            _packageService = packageService;
            _currentUser = currentUser;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string id)
        {
            var packages = await _packageService.AllPackages(_currentUser.GetUserId(User));
            
            return View(packages);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

04.C#Web/C# MVC Frameworks - ASP.NET Core/05.ExerciseIntroductionToASP.NetCore/Panda/Panda.Web/Panda.Web/Controllers/PackagesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Panda.Common.ViewModels.Packages;
using Panda.Model;
using Panda.Services.Contracts;

namespace Panda.Web.Controllers
{
    public class PackagesController : Controller
    {
        private readonly IPackageService _packageService;
        private readonly UserManager<PandaUser> _currentUser;

        public PackagesController(IPackageService packageService, UserManager<PandaUser> currentUser)
        {
            _packageService = packageService;
            _currentUser = currentUser;

        }

        [Authorize]
        public async Task<IActionResult> Details(Guid id)
        {
            var packageDetails = await _packageService.Details(id, _currentUser.GetUserId(User));
            return View(packageDetails);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CreatePackage()
        {
            var viewModel = _packageService.GetUserNamesPackage();

            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreatePackage(CreatePackageViewModel model)
        {
            await _packageService.CreatePackage(model);
            return RedirectToAction("AllPending");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AllPending()
        {
            var allPending = _packageService.AllPending();

            return View("AllPending", allPending);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Ship(Guid id)
        {
            await _packageService.Ship(id);

            return RedirectToAction("AllShipped");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AllShipped()
        {
            var allShipped = _packageService.AllShipped();

            return View("AllShipped", allShipped);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Deliver(Guid id)
        {
            await _packageService.Deliver(id);

            return RedirectToAction("AllDelivered");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AllDelivered()
        {
            var allDelivered = _packageService.AllDelivered();

            return View("AllDelivered", allDelivered);
        }
    }
}

04.C#Web/C# MVC Frameworks - ASP.NET Core/05.ExerciseIntroductionToASP.NetCore/Panda/Panda.Web/Panda.Web/Controllers/ReceiptsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Panda.Model;
using Panda.Services.Contracts;

namespace Panda.Web.Controllers
{
    public class ReceiptsController : Controller
    {
        private readonly IReceiptService _receiptService;
        private readonly UserManager<PandaUser> _currentUser;

        public ReceiptsController(IReceiptService receiptService, UserManager<PandaUser> currentUser)
        {
            _receiptService = receiptService;
            _currentUser = currentUser;
        }

        public async Task<IActionResult> Index()
        {
            var receipts = await _receiptService.AllCurrentUserReceipts(_currentUser.GetUserId(User));

            return View("Index", receipts);
        }

        public async Task<IActionResult> ReceiptDetails(Guid id)
        {
            var receiptDetails = await _receiptService.Details(id, _currentUser.GetUserId(User));

            return View(receiptDetails);
        }

        public async Task<IActionResult> Acquire(Guid id)
        {
           var receiptDetails =  await _receiptService.CreateReceipt(id, _currentUser.GetUserId(User));

            return View("ReceiptDetails", receiptDetails);
        }
    }
}

04.C#Web/C# MVC Frameworks - ASP.NET Core/05.ExerciseIntroductionToASP.NetCore/Panda/Panda.Web/Panda.Web/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Panda.Model
@model Panda.Common.ViewModels.Packages.PackagesViewModel
@inject SignInManager<PandaUser> SignInManager
@inject UserManager<PandaUser> UserManager
@inject RoleManager<IdentityRole> RoleManager
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (SignInManager.IsSignedIn(User))
{
    if (User.IsInRole("Admin"))
    {
        <h1 class="text-center">Hello, Administrator @UserManager.GetUserName(User)!</h1>
    }
    else
    {
        <h1 class="text-center">Hello, @UserManager.GetUserName(User)!</h1>
    }
    <hr class="bg-dark hr-2" />
    <div class="row">
        <div class="col-sm-3 mx-5">
            <h3 class="text-center">Pending</h3>
            <div class="border-panda">
                @foreach (var package in Model.PendingPackages)
                {
                    <div class="card-body row py-2">
                        <h5 class="card-title col-md-9">@package.Name</h5>
                        <a asp-controller="Packages" asp-action="Details" asp-route-id="@package.Id" class="btn btn-primary col-md-3 bg-dark">Details</a>
                    </div>
                }
            </div>
        </div>
        <div class="col-sm-3 mx-5 justify-content-center">
            <h3 class="text-center">Shipped</h3>
            <div class="border-panda">
                @foreach (var package in Model.ShippedPackages)
                {
                    <div class="card-body row py-2">
                        <h5 class="card-title col-md-9">@package.Name</h5>
                        <a asp-controller="Packages" asp-action="Details" asp-route-id="@package.Id" class="btn btn-primary col-md-3 bg-dark">Details</a>
                    </div>
                }
            </div>
        </div>
        <div class="col-sm-3 ml-5">
            <h3 class="text-center">Delivered</h3>
            <div class="border-panda">
                @foreach (var package in Model.DeliveredPackages)
                {
                    <div class="card-body row py-2">
                        <h5 class="card-title col-md-9">@package.Name</h5>
                        <a asp-controller="Receipts" asp-action="Acquire" asp-route-id="@package.Id" class="btn btn-primary col-md-3 bg-dark">Acquire</a>
                    </div>
                }
            </div>
        </div>
    </div>
}
else
{
    <div class="jumbotron mt-3 bg-panda">
        <h1 class="text-white">Welcome to PANDA Delivery Services.</h1>
        <hr class="bg-white hr-2" />
        <h3 class="text-white"><a asp-area="Identity" asp-page="/Account/Login">Login</a> if you have an account.</h3>
        <h3 class="text-white"><a asp-area="Identity" asp-page="/Account/Register">Register</a> if you don't.</h3>
    </div>
}